Dg tracker view
karibou-ch/kio2-admin pull request #5
Opened 2017-07-10 07:47 UTC by GonzalD

Bouton map sur page livraison, quand un jour de livraison est selectionné.

Avec Leaflet.

2017-07-10 13:10 UTC, evaletolab requested changes
qq questions, merci!

2017-07-10 13:10 UTC, evaletolab commented on src/pages/tracker/tracker.ts
> +      accessToken: 'pk.eyJ1IjoiZ29uemFsZCIsImEiOiJjajR3cW5ybHQwZ3RrMzJvNXJrOWdkbXk5In0.kMW6xbKtCLEYAEo2_BdMjA'
on ne peut pas mettre le token dans le code comme ça, utilise default config provider !

2017-07-10 13:10 UTC, evaletolab commented on src/providers/tracker/tracker.provider.ts
> +      desiredAccuracy: 100,
tu peux documenter, ou placer le lien en comment de ce est le mieux pour une petite consommation d'énergie?

2017-07-10 13:10 UTC, evaletolab commented on src/providers/tracker/tracker.provider.ts
> +    // this.backgroundLocation$.unsubscribe();
pourquoi tu comment le stop?

2017-07-10 13:22 UTC, evaletolab requested changes
encore un détail

2017-07-10 13:22 UTC, evaletolab commented on src/pages/tracker/tracker.html
> +        <button [disabled]="!isReady" ion-button icon-only clear="true" (click)="allOrdersZoom()">
nein! dans  le navbar please !

2017-07-10 14:40 UTC, GonzalD commented on src/providers/tracker/tracker.provider.ts
> +    // this.backgroundLocation$.unsubscribe();
Parce que mon component n'utilise pas (encore) le background location mais uniquement le foreground location pour l'instant (le seul testable sur navigateur).

Je décommenterai quand on l'utilisera (si on le remplace pas par le système hypertrack)

2017-07-10 16:20 UTC, evaletolab commented on src/providers/tracker/tracker.provider.ts
> +    // this.backgroundLocation$.unsubscribe();
ok!

2017-07-10 16:21 UTC, evaletolab commented
ERROR:
`No value provided for variable {accessToken}`

2017-08-24 14:33 UTC, evaletolab requested changes
hello, super simple maintenant. Quelques notes:
- remplacé filtre url pour commandes fermée/ouverte avec  (ouverte== authorized, fermée==paid)
- sélectionner la date par défaut (currentShippingDay() ou dernière date de la liste)
- enlever l'icon fullscreen de google map
- dans la carte, le zoom de la carte n'est pas à la bonne valeur
- dans la carte, il n'y a pas le même nombre de icon que de livraison??
- dans la carte, BUG: co.trackMe is not a function
- dans la carte, BUG: co.allOrdersZoom is not a function

Ok pour toi? merci David

2017-08-29 08:47 UTC, evaletolab requested changes
Excellent!!! deux choses encore,
* dans la carte il n'y a pas le même nombre de livraisons affiché
* la geolocalisation est afficher la première fois, si on change de date, on ne voit pas sa position
* le zoom sur les livraisons proches doit être un toggle (zoom/in, ou zoom/out)

2017-08-29 13:24 UTC, evaletolab approved these changes

2017-08-29 13:24 UTC, merged