Dg collecte page header component heritance
karibou-ch/kio2-admin pull request #7
Opened 2017-08-31 15:47 UTC by GonzalD

Separated header code from shopper to header-logistic component (data transmitted with event)

2017-08-31 19:28 UTC, evaletolab requested changes

2017-08-31 19:28 UTC, evaletolab commented on src/components/logistic-header/logistic-header.ts
> +  monthCommands: Map<number, Shop[]> = new Map();
monthCommands; on peut l'enlever celui-ci?

2017-08-31 19:28 UTC, evaletolab commented on src/components/logistic-header/logistic-header.ts
> +    public navCtrl: NavController,
il est utilisé navCtrl?

2017-09-01 09:30 UTC, GonzalD commented on src/components/logistic-header/logistic-header.ts
> +  monthCommands: Map<number, Shop[]> = new Map();
Oui sans soucis. Je l'avais mis parce que je pensais qu'on en aurait besoin pour les commandes.

2017-09-01 12:56 UTC, evaletolab commented on src/components/logistic-header/logistic-header.ts
> +  monthCommands: Map<number, Shop[]> = new Map();
tu fais la modif, et on ferme le pr :+1:

2017-09-03 17:50 UTC, evaletolab approved these changes

2017-09-03 17:50 UTC, merged